lsi: false
safe: true
source: 
incremental: false
highlighter: rouge
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Deyan Kong
description: Personal Homepage
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
